services:
  banco:
    container_name: blogpessoal-db
    image: postgres:16.1
    environment:
      - POSTGRES_USER=usuario
      - POSTGRES_PASSWORD=pass
      - POSTGRES_DB=blogpessoal
    networks:
      - services
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  blogpessoal:
    container_name: blogpessoal-api
    depends_on:
      banco:
        condition: service_started
    build:
      context: ../
      dockerfile: ./backend/Dockerfile
    ports:
      - "8080:8080"
    networks:
      - services

volumes:
  pgdata:
    driver: local

networks:
  services:
    name: services