services:
  banco_app:
    container_name: blogpessoal-db
    image: postgres:16.1
    environment:
      - POSTGRES_USER=luisguerreiro
      - POSTGRES_PASSWORD=acelera
      - POSTGRES_DB=blogpessoal
    networks:
      - services
    ports:
      - "5432:5432"
    volumes:
      - pgdata_app:/var/lib/postgresql/data

  blogpessoal:
    container_name: blogpessoal-api
    depends_on:
      banco_app:
        condition: service_started
    build:
      context: ../
      dockerfile: /Dockerfile
    ports:
      - "8080:8080"
    networks:
      - services