services:
  banco_app:
    container_name: blogpessoal-db
    image: postgres:16.1
    environment:
      - POSTGRES_USER=luisguerreiro
      - POSTGRES_PASSWORD=acelera
      - POSTGRES_DB=blogpessoal
    networks:
      - services
    ports:
      - "5432:5432"
    volumes:
      - pgdata_app:/var/lib/postgresql/data

  banco_sonar:
    container_name: sonarqube-db
    image: postgres:16.1
    environment:
      - POSTGRES_USER=sonaruser
      - POSTGRES_PASSWORD=sonarpass
      - POSTGRES_DB=sonarqube
    networks:
      - services
    volumes:
      - pgdata_sonar:/var/lib/postgresql/data

  blogpessoal:
    container_name: blogpessoal-api
    depends_on:
      banco_app:
        condition: service_started
    build:
      context: ../
      dockerfile: /Dockerfile
    ports:
      - "8080:8080"
    networks:
      - services
  sonarqube:
    container_name: sonarqube
    image: sonarqube:latest
    depends_on:
      - banco_sonar
    environment:
      - SONAR_JDBC_URL=jdbc:postgresql://banco_sonar:5432/sonarqube
      - SONAR_JDBC_USERNAME=sonaruser
      - SONAR_JDBC_PASSWORD=sonarpass
    ports:
      - "9000:9000"
    networks:
      - services
    volumes:
      - sonarqube_data:/opt/sonarqube/data
      - sonarqube_